services:
  - type : database 
    name: mongodb
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - name: mongodb_data
        path: /data/db

  - type: web
    name: java_app
    buildCommand: docker build -t your-java-app .
    startCommand: docker run -p 8080:8080 your-java-app
    envVars:
      SPRING_DATA_MONGODB_HOST: mongodb
      SPRING_DATA_MONGODB_PORT: "27017"
    envVarsFrom:
      - mongodb
    ports:
      - 8080
